# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guess.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(988, 576)
        self.texting_box = QtWidgets.QTextEdit(Form)
        self.texting_box.setGeometry(QtCore.QRect(820, 90, 151, 311))
        self.texting_box.setObjectName("texting_box")
        self.button_send = QtWidgets.QPushButton(Form)
        self.button_send.setGeometry(QtCore.QRect(820, 410, 151, 91))
        self.button_send.setObjectName("button_send")
        self.players = QtWidgets.QLabel(Form)
        self.players.setGeometry(QtCore.QRect(20, 100, 141, 391))
        self.players.setFrameShape(QtWidgets.QFrame.Box)
        self.players.setText("")
        self.players.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.players.setObjectName("players")
        self.dialog = QtWidgets.QLabel(Form)
        self.dialog.setGeometry(QtCore.QRect(170, 100, 621, 391))
        self.dialog.setFrameShape(QtWidgets.QFrame.Box)
        self.dialog.setText("")
        self.dialog.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.dialog.setObjectName("dialog")
        self.status = QtWidgets.QLabel(Form)
        self.status.setGeometry(QtCore.QRect(20, 10, 771, 71))
        self.status.setFrameShape(QtWidgets.QFrame.Box)
        self.status.setText("")
        self.status.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.status.setObjectName("status")
        self.button_start = QtWidgets.QPushButton(Form)
        self.button_start.setGeometry(QtCore.QRect(820, 10, 151, 71))
        self.button_start.setObjectName("button_start")

        self.retranslateUi(Form)
        self.button_send.clicked.connect(Form.send_msg) # type: ignore
        self.button_start.clicked.connect(Form.guess_start) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Guess"))
        self.button_send.setText(_translate("Form", "发送"))
        self.button_start.setText(_translate("Form", "开始"))
